// Generated by Apple Swift version 4.0.2 effective-3.2.2 (swiftlang-900.0.69.2 clang-900.0.38)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("Ncncd")

SWIFT_CLASS("_TtC5Ncncd11BloodOxygen")
@interface BloodOxygen : NSObject
@property (nonatomic) float average;
@property (nonatomic) float max;
@property (nonatomic) float min;
@property (nonatomic) NSInteger beginTime;
@property (nonatomic) NSInteger endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd14BloodOxygenApi")
@interface BloodOxygenApi : NSObject
/// 上传血氧数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 血氧数据
///
/// \param telephone 电话
///
+ (void)uploadBloodOxygenWithData:(NSArray<BloodOxygen *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd13BloodPressure")
@interface BloodPressure : NSObject
@property (nonatomic) NSInteger diastolic;
@property (nonatomic) NSInteger systolic;
@property (nonatomic) NSInteger sampleTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd16BloodPressureApi")
@interface BloodPressureApi : NSObject
/// 上传血压数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 血压数据
///
/// \param telephone 电话
///
+ (void)uploadBloodPressureWithData:(NSArray<BloodPressure *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd10BloodSugar")
@interface BloodSugar : NSObject
@property (nonatomic) NSInteger type;
@property (nonatomic) float value;
@property (nonatomic) NSInteger sampleTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd13BloodSugarApi")
@interface BloodSugarApi : NSObject
/// 上传血糖数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 血糖数据
///
/// \param telephone 电话
///
+ (void)uploadBloodSugarWithData:(NSArray<BloodSugar *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd6Health")
@interface Health : NSObject
@property (nonatomic) float bmi;
@property (nonatomic) float bodyFat;
@property (nonatomic) float muscleRate;
@property (nonatomic) float moistureRate;
@property (nonatomic) float bmd;
@property (nonatomic) float bmr;
@property (nonatomic) NSInteger sampleTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd9HealthApi")
@interface HealthApi : NSObject
/// 上传健康数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 健康数据
///
/// \param telephone 电话
///
+ (void)uploadHealthWithData:(NSArray<Health *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd9HeartRate")
@interface HeartRate : NSObject
@property (nonatomic) float average;
@property (nonatomic) float max;
@property (nonatomic) float min;
@property (nonatomic) NSInteger beginTime;
@property (nonatomic) NSInteger endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd12HeartRateApi")
@interface HeartRateApi : NSObject
/// 上传心率数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 心率数据
///
/// \param telephone 电话
///
+ (void)uploadHeartRateWithData:(NSArray<HeartRate *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd14NcncdConfigure")
@interface NcncdConfigure : NSObject
/// 初始化配置
/// \param appKey appKey
///
/// \param appSecret appSecret
///
+ (void)initConfigureWithAppKey:(NSString * _Nonnull)appKey appSecret:(NSString * _Nonnull)appSecret SWIFT_METHOD_FAMILY(none);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITouch;
@class UIEvent;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC5Ncncd15NcncdRegisterVC")
@interface NcncdRegisterVC : UIViewController
- (void)viewDidLoad;
/// 回收键盘
/// \param touches 
///
/// \param event 
///
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd5Sleep")
@interface Sleep : NSObject
@property (nonatomic) NSInteger totalDuration;
@property (nonatomic) NSInteger effectiveDuration;
@property (nonatomic) NSInteger deepDuration;
@property (nonatomic) NSInteger lightDuration;
@property (nonatomic) NSInteger beginTime;
@property (nonatomic) NSInteger endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd8SleepApi")
@interface SleepApi : NSObject
/// 上传睡眠数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 睡眠数据
///
/// \param telephone 电话
///
+ (void)uploadSleepWithData:(NSArray<Sleep *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd5Sport")
@interface Sport : NSObject
@property (nonatomic) NSInteger step;
@property (nonatomic) NSInteger distance;
@property (nonatomic) NSInteger beginTime;
@property (nonatomic) NSInteger endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd8SportApi")
@interface SportApi : NSObject
/// 上传运动数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 运动数据
///
/// \param telephone 电话
///
+ (void)uploadSportWithData:(NSArray<Sport *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd11Temperature")
@interface Temperature : NSObject
@property (nonatomic) float average;
@property (nonatomic) float max;
@property (nonatomic) float min;
@property (nonatomic) NSInteger beginTime;
@property (nonatomic) NSInteger endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5Ncncd14TemperatureApi")
@interface TemperatureApi : NSObject
/// 上传体温数据
/// \param appKey AppKey
///
/// \param appSecret AppSecret
///
/// \param data 体温数据
///
/// \param telephone 电话
///
+ (void)uploadTemperatureWithData:(NSArray<Temperature *> * _Nonnull)data telephone:(NSString * _Nonnull)telephone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
